[settings]
idiomatic_version_file_enable_tools = []

[tools]
"node" = ["lts"]


# "java" = ["corretto-24", "corretto-21", "corretto-8"]
# "maven" = ["3.9.9", "latest"]
# "scala" = ["2.13.16", "3"]
# "aws-cli" = "latest"
# "python" = "latest"
# "pipx" = "latest"
# "uv" = "latest"
