# general.import = ["./themes/doom_one.toml"]
general.import = ["./themes/duskfox.toml"]
# general.import = ["./themes/palenight.toml"]
# general.import = ["./themes/tender.toml"]
# general.import = ["./themes/wombat.toml"]

[env]
TERM = "alacritty"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[window]
padding.x = 10
padding.y = 10
decorations = "None"
option_as_alt = "Both"
# opacity = 0.94

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" },
]
