[env]
TERM = "alacritty"

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[window]
padding.x = 4
padding.y = 4
decorations = "None"
option_as_alt = "Both"
# opacity = 0.94

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\n" }]

[general]
import = ["~/.config/alacritty/themes/tender.toml"]
