[env]
TERM = "alacritty"

[font]
size = 16
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
# bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
# italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[window]
padding.x = 4
padding.y = 4
decorations = "None"
option_as_alt = "Both"
# opacity = 0.94

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\n" }]
