## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = """
$directory\
$git_branch $git_state$git_status\
$jobs\
$java$nodejs$gleam$haskell$python\
$fill$shell\
$line_break$sudo$character\
"""

[directory]
style = "italic blue"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style)"
style = "dimmed blue"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[shell]
disabled = false
format = '[$indicator]($style)'
style = "bright-black"
zsh_indicator = "zsh"
bash_indicator = "bash"

[sudo]
disabled = false
format = "[$symbol]($style)"
style = "blue"
symbol = "#"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](dimmed red)"
vimcmd_symbol = "[❮](purple)"

[java]
disabled = false
symbol = " "

[nodejs]
disabled = false
symbol = " "

[gleam]
disabled = false

[haskell]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "
